#!/bin/bash 
 
#This script is built to monitor processes without using the top command. 
#It also monitors for malicious scripts. 
#This is accomplished with 30 second snapshots of the running processes. 
#The differences are output to the file proc.lst 
 
#while ((i=0,i < 6, i++)); do 
 
baseline=$(ps > /home/Burgess/Desktop/procmonix/baseline.txt) 
 
bash 
 
sleep 30 
 
comparison=$(ps > /home/Burgess/Desktop/procmonix/comparison.txt) 
 
if [[ $baseline_$i -eq $comparison ]] ; then 
    echo "Running process HAVE NOT changed." 
else 
    echo "Running process HAVE changed." 
 
    date >> /home/Burgess/Desktop/procmonix/procmonix/proc.lst 
    diff baseline.txt comparison.txt >> /home/Burgess/Desktop/procmonix/proc.lst 
 
    echo "Here are the changes.." 
 
    cat /home/Burgess/Desktop/procmonix/procmonix/proc.lst 
fi 
 
exit 
 
#done 
