#!/bin/bash 
 
#There is no need to run this script. It is run from within the l2skills.sh script. 
 
if [ $# -lt 2 ] ; 
then 
    echo usage : $0 protocols $2 
    exit 1 
fi 
 
filename=$1 
namp_results=$2 
filelines=`cat $filename` 
 
for proto in $filelines ; do 
    echo 
    echo $proto 
    echo "====================" 
    cat $2 | grep -B20 $proto > results.txt 
    grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' results.txt 
done 
